### ISSUE TITLE
Implement "Run" button

### ISSUE THREAD

**Issue by rlaemmel** [avaranovich/megal-xtext#17]
For now, we already do sort of well-formedness and -definedness as in the ECMFA paper.

In the next version (soon), we should have an explicit "Run" button to check links, run all resolvers with their dispatchers.

In a version beyond this issue (and perhaps much later), we could have the "run" actions being executed smartly upon "save". It needs to "smart" (by means of memo, for example) because otherwise the costs of each save could be too high easily. But again, this is not urgent from a user experience's point of view and can be deferred "indefinitely".

**Comment by lukashaertel** [comment]
Works through validation, URL connections are cached
