### ISSUE TITLE
Move repo to https://github.com/softlang

### ISSUE THREAD

**Issue by maxmeffert** [avaranovich/megal-xtext#27]
This issue is meant as a simple reminder.
As far as I know this is planned for some while, but nothing happened yet.
Someone with admin privileges has to move this repo.
Maybe Lukas has those privileges or we need to contact Andrej.
We should confirm this with Ralf before someone acts.

**Comment by le-cram** [comment]
closed, though I don't have permissions to close :-) 
see https://github.com/softlang/megal-xtext
