### ISSUE TITLE
Languages are not linked by default

### ISSUE THREAD

**Issue by avaranovich** [avaranovich/megal-xtext#4]
Consider the following megamodel
```
model Java configured in Config
import Prelude

Java : Language
javaProgram : File
```
with the following configuration
```
configuration Config for Java
jar "/technomodels/plugins/megal-0.0.1-SNAPSHOT.jar"
provider dbpedia
```

the following provider should link Java language to a dbpedia page
https://github.com/avaranovich/megal/blob/master/eclipse/megal/src/main/java/megal/providers/dbpedia.java

**Comment by lukashaertel** [comment]
Does link for existing dbpedia pages
